In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1、读取数据
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"
column_name = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                   'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                   'Normal Nucleoli', 'Mitoses', 'Class']

data = pd.read_csv(path, names=column_name)

In [4]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [7]:
# 2、缺失值处理
# 1）替换-》np.nan
data = data.replace(to_replace="?", value=np.nan)
# 2）删除缺失样本
data.dropna(inplace=True)

In [9]:
data.isnull().any() # 不存在缺失值

Sample code number             False
Clump Thickness                False
Uniformity of Cell Size        False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
Class                          False
dtype: bool

In [10]:
# 3、划分数据集
from sklearn.model_selection import train_test_split

In [11]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [12]:
# 筛选特征值和目标值
x = data.iloc[:, 1:-1]
y = data["Class"]

In [14]:
x.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                5                        1                         1   
1                5                        4                         4   
2                3                        1                         1   
3                6                        8                         8   
4                4                        1                         1   

   Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
0                  1                            2           1   
1                  5                            7          10   
2                  1                            2           2   
3                  1                            3           4   
4                  3                            2           1   

   Bland Chromatin  Normal Nucleoli  Mitoses  
0                3                1        1  
1                3                2        1  
2                3                1        1  
3                3                7        1  
4                3                1        1

In [16]:
y.head()

0    2
1    2
2    2
3    2
4    2
Name: Class, dtype: int64

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [19]:
x_train.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
71                 6                       10                         2   
413                5                        1                         2   
159                9                        9                        10   
371                1                        1                         3   
331                5                        1                         1   

     Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
71                   8                           10           2   
413                  1                            2           1   
159                  3                            6          10   
371                  1                            2           1   
331                  1                            2           1   

     Bland Chromatin  Normal Nucleoli  Mitoses  
71                 7                8       10  
413                3                1        1  
159                7               10        6  
371                1                1        1  
331                3                1        2

In [20]:
# 4、标准化
from sklearn.preprocessing import StandardScaler

In [21]:
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

/Users/zwy/.virtualenvs/python4/lib/python3.6/site-packages/sklearn/preprocessing/data.py:617: DataConversionWarning: Data with input dtype int64, object were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/zwy/.virtualenvs/python4/lib/python3.6/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, object were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/Users/zwy/.virtualenvs/python4/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, object were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until


In [22]:
x_train

array([[ 0.55384961,  2.25850408, -0.39241988, ...,  1.48150122,
         1.58884606,  4.5986847 ],
       [ 0.20071013, -0.68803805, -0.39241988, ..., -0.17196717,
        -0.61573167, -0.34779968],
       [ 1.61326804,  1.93111051,  2.29545943, ...,  1.48150122,
         2.21872542,  2.4002472 ],
       ...,
       [-0.50556882, -0.68803805, -0.72840479, ..., -0.99870137,
        -0.61573167, -0.34779968],
       [ 0.20071013,  2.25850408,  2.29545943, ...,  0.65476703,
         2.21872542,  0.75141907],
       [ 1.96640752,  0.29414266,  0.27954995, ...,  0.65476703,
         0.01414768,  0.75141907]])

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
# 5、预估器流程
estimator = LogisticRegression()
estimator.fit(x_train, y_train)

/Users/zwy/.virtualenvs/python4/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [25]:
# 逻辑回归的模型参数：回归系数和偏置
estimator.coef_

array([[1.39074328, 0.24254804, 0.77224014, 0.74201473, 0.23764145,
        1.04861389, 0.90381812, 0.53872577, 0.90103902]])

In [26]:
estimator.intercept_

array([-1.18507135])

In [27]:
# 6、模型评估
# 方法1：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print("y_predict:\n", y_predict)
print("直接比对真实值和预测值:\n", y_test == y_predict)

# 方法2：计算准确率
score = estimator.score(x_test, y_test)
print("准确率为：\n", score)

y_predict:
 [2 2 2 2 4 4 2 2 2 2 4 4 2 4 2 2 4 2 4 4 2 2 4 4 2 4 2 2 4 2 2 2 2 4 2 4 4
 4 2 2 4 2 4 4 2 2 2 4 4 2 2 2 2 2 2 4 4 2 2 2 4 4 4 2 4 2 4 2 2 2 2 2 4 2
 4 4 2 2 4 2 2 2 2 2 2 4 4 4 2 2 2 2 2 2 2 2 2 2 4 4 4 4 4 2 2 2 2 2 2 4 2
 2 4 4 2 4 2 2 2 2 2 2 2 2 2 2 2 2 2 2 4 2 2 2 2 2 4 2 4 4 2 4 2 2 4 4 4 4
 2 4 2 2 4 4 2 2 2 4 2 2 2 4 4 2 2 2 2 2 2 4 2]
直接比对真实值和预测值:
 432     True
256     True
203     True
281     True
588     True
590     True
66      True
473     True
637     True
537     True
103     True
334     True
8       True
44      True
141     True
90      True
329     True
454     True
440     True
200     True
665     True
495     True
279     True
272     True
43     False
282     True
22      True
548     True
330     True
654     True
       ...  
340     True
470     True
343     True
253     True
264     True
262     True
132     True
51     False
42      True
250     True
651     True
232    False
581     True
94      True
385     True
566     True
386     True
23

In [28]:
# 查看精确率、召回率、F1-score
from sklearn.metrics import classification_report

In [29]:
report = classification_report(y_test, y_predict, labels=[2, 4], target_names=["良性", "恶性"])

In [31]:
print(report)

              precision    recall  f1-score   support

          良性       0.95      0.99      0.97       107
          恶性       0.98      0.92      0.95        64

   micro avg       0.96      0.96      0.96       171
   macro avg       0.97      0.96      0.96       171
weighted avg       0.97      0.96      0.96       171



In [33]:
y_test.head()

432    2
256    2
203    2
281    2
588    4
Name: Class, dtype: int64

In [34]:
# y_true：每个样本的真实类别，必须为0(反例),1(正例)标记
# 将y_test 转换成 0 1
y_true = np.where(y_test > 3, 1, 0)

In [35]:
y_true

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0])

In [36]:
from sklearn.metrics import roc_auc_score

In [37]:
roc_auc_score(y_true, y_predict)

0.9562646028037384